### ISSUE TITLE
Color blocks problem of ERP format data

### ISSUE THREAD

**Issue by dypromise** [castacks/tartanairpy#28]
Hi，
I try tests/tartanairpy_test.py and modify the data format to 'lcam_equirect', I found that there are many images that have the problem of color blocks,  how to fix it?
![000012_lcam_equirect_image](https://github.com/castacks/tartanairpy/assets/21032349/117f6acd-a00d-4ebd-b12b-468d21c93aa2)
![000005_lcam_equirect_image (1)](https://github.com/castacks/tartanairpy/assets/21032349/b85a9d9a-c486-485c-ba2b-89f9d2670bf3)

**Comment by yoraish** [comment]
Hey dypromise! Thanks for opening this issue.

When you say "color blocks," I am assuming that you mean some areas of the image seem to be slightly brighter -- and that these areas appear in a square-block shape. You are right that it happens sometimes. It is a result of how we generate new image modalities: by stitching together raw images pointing in different directions into one panoramic image, for example. The specific instances when this happens are when one or more sides of the image are facing strong light sources (like the sun), and lens flares are generated for individual raw images. When those are stitched, the seam shows sometimes, even though we worked to minimize the effects of brightness on stitching. For context, we chose to keep this feature to make the raw images more realistic.

If you end up writing code for this and would like to contribute, we would love it if you could open a pull request!
