### ISSUE TITLE
Failed to download dataset

### ISSUE THREAD

**Issue by letsgofeng** [castacks/tartanairpy#32]
The download dataset prompts AuthenticationFailed, what is the reason?
See below for details：

azcopy copy "https://tartanairv2.blob.core.windows.net/data-raw/ModularNeighborhoodIntExt/analyze/?sv=2021-10-04&st=2023-03-01T16%3A34%3A50Z&se=2023-03-30T15%3A34%3A00Z&sr=c&sp=rl&sig=LojCTa60TcA9ApMiMofliedxujeX0AOZdoC3O5u5cxg%3D" F:/tartanair-v2/ --recursive --as-subdir=true --include-pattern 'data_*.txt;motion_*.npy'
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, C:/Users/VssAdministrator/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)
   HEAD https://tartanairv2.blob.core.windows.net/data-raw/ModularNeighborhoodIntExt/analyze?se=2023-03-30t15%3A34%3A00z&sig=-REDACTED-&sp=rl&sr=c&st=2023-03-01t16%3A34%3A50z&sv=2021-10-04&timeout=901
   User-Agent: [AzCopy/10.19.0 Azure-Storage/0.15 (go1.19.8; Windows_NT)]
   X-Ms-Client-Request-Id: [f1aa372e-b3b3-4ea5-7485-d7c444719aec]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Connection: [Keep-Alive]
   Date: [Tue, 27 Jun 2023 04:44:46 GMT]
   Proxy-Connection: [Keep-Alive]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [cdc3331c-d01e-0038-28b2-a8443e000000]

**Comment by yoraish** [comment]
Hi! This version of TartanAir is not officially released yet -- so access may not be available. If you are a collaborator, please reach out to me or @Amigoshan directly. Otherwise, check back soon! :)

**Comment by Parskatt** [comment]
@yoraish Hi! I'm checking back soon and wondering how the progress is going?
